### ISSUE TITLE
Consider referring to python-igraph instead of igraph

### ISSUE THREAD

**Issue by szhorvat** [larslorch/dibs#7]
Please consider referring to `igraph` instead of `python-igraph` in the following three locations:

https://github.com/search?q=repo%3Alarslorch%2Fdibs%20python-igraph&type=code

and dropping the pin to version 0.8.3, which is extremely outdated. Behaviour changes since then are mainly the result of bugfixes. If there is a behaviour change that affects this project, feel free to open an issue in the python-igraph repo and ask about it.

The python-igraph name is deprecated on PyPI and will soon cease to receive updates. See https://github.com/igraph/python-igraph/issues/699 for details. However, the first version available under the `igraph` name is 0.9.8 from October 2021. 0.8.3 (current pin) is not available under this name.

**Comment by larslorch** [comment]
Done!
